version = 1

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = ["/build"]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "csharp"

[[transformers]]
name = "dotnet-format"